name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  tests:
    name: "Python ${{ matrix.python-version }} / Pydantic ${{ matrix.pydantic-version }}"
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        pydantic-version: ["2.8.2", "2.9.2", "2.10.6", "2.11.7", "2.12.4"]
        exclude:
          - python-version: "3.14"
            pydantic-version: "2.8.2"
          - python-version: "3.14"
            pydantic-version: "2.9.2"
          - python-version: "3.14"
            pydantic-version: "2.10.6"
          - python-version: "3.14"
            pydantic-version: "2.11.7"

    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.2"
          enable-cache: true

      - run: uv sync --frozen --extra dev

      - name: Install pydantic ${{ matrix.pydantic-version }}
        run: uv pip install pydantic==${{ matrix.pydantic-version }}

      - name: Test with pytest
        env:
          COVERAGE_FILE: coverage-data-${{ matrix.python-version }}-pydantic-${{ matrix.pydantic-version}}
        run: uv run --no-sync --frozen coverage run -m pytest

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ matrix.python-version }}-pydantic-${{ matrix.pydantic-version}}
          path: coverage-data-${{ matrix.python-version }}-pydantic-${{ matrix.pydantic-version}}*


  tests-lowest:
    name: "Python ${{ matrix.python-version }} / lowest"
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.2"
          enable-cache: true

      - run: uv lock --resolution lowest-direct

      - run: uv sync --frozen --extra dev

      - name: Test with pytest
        env:
          COVERAGE_FILE: coverage-data-${{ matrix.python-version }}-lowed
        run: uv run --no-sync --frozen coverage run -m pytest

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ matrix.python-version }}-lowest
          path: coverage-data-${{ matrix.python-version }}-lowest*

  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    needs:
      - tests
      - tests-lowest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.2"
          enable-cache: true

      - run: uv sync --frozen --extra dev

      - name: Download data
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-data-*
          merge-multiple: true

      - name: Combine coverage
        # Combines all the downloaded coverage artifacts in a single `.coverage` file,
        # which will then be used by `py-cov-action/python-coverage-comment-action`.
        # We added this step to replace the variable `MERGE_COVERAGE_FILES: true`
        # in the next step, which had started to raise errors
        # (https://github.com/fractal-analytics-platform/fractal-server/pull/1725).
        run: uv run --frozen coverage combine coverage-data-*

      - name: Add coverage comment to Pull Requests
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 60
          ANNOTATE_MISSING_LINES: true
          ANNOTATION_TYPE: notice
